### ISSUE TITLE
Specify a diff threshold

### ISSUE THREAD

**Issue by Corvwyn** [red6/pdfcompare#12]
I'm regression testing a lot of PDFs that are rendered to and from many different formats, so there will always be a certain diff. 

At the moment I have to go through every file manually to ensure that the diff isn't too large, which is quite time consuming. 

It would be very useful if I could specify that a 2 mm difference would be ok, for example. Would this be possible to implement?

**Comment by finsterwalder** [comment]
I don't quite understand what you mean by "2mm difference"?
Do you mean the page is identical, but it's moved a little to the left or to the right?

In general it would of course be possible to allow for some kind of "difference". But what kind of difference?
Some examples I can come up with from the top of my head:
- Less than n% of the page differs
- No more than n consequtive pixels differ (probably more complicated to implement)
- ...?!

**Comment by Corvwyn** [comment]
Thanks for responding so quickly.

Yeah, I mean that a piece of text, or an image could be allowed to be moved a little. The most practical measurement would probably be millimeters. 

Usually for us, a couple of millimeters is ok, but 1 cm is too much. If the name and address is moved for example, the address isn't visible in the envelope window.

**Comment by finsterwalder** [comment]
That's not trivial, or at least I don't have a simple idea, how to do that.
The program would have to find an "alignment": How many pixels was the image moved.
The idea that comes to my mind is: move the image one pixel and recompare. You would have to do this n times, until you moved more than 1cm for example.
Very time consuming and not so simple to implement.

**Comment by finsterwalder** [comment]
Some other ideas:
Does your movement move the whole page my a few millimeters?
Does the movement change on every run of your tests and always comes out differently?
Can you process your PDFs and generate all the expected PDFs and use them for comparison in the next run?
Can you use an ignore area where the envelope window is and thereby detect any overruns?
...

**Comment by Corvwyn** [comment]
> The idea that comes to my mind is: move the image one pixel and recompare. You would have to do this n times, until you moved more than 1cm for example.

Yes, this sounds like they way you'd have to do it.

> Does your movement move the whole page my a few millimeters?

I haven't seen this case before. There's usually only one or more blocks that are moved, and not the whole page.

> Does the movement change on every run of your tests and always comes out differently?

Don't know if this is a common occurence. It's usually always the same diff.

> Can you process your PDFs and generate all the expected PDFs and use them for comparison in the next run?

I'm not quite sure what you mean here.

> Can you use an ignore area where the envelope window is and thereby detect any overruns?

This would certainly cover this specific issue, but there's usually more than just this. It's certainly an improvement though.

**Comment by finsterwalder** [comment]
The process I use is:
I let my system generate all the PDFs from my inputs.
I verify the generated PDFs by hand.
I store all the PDFs as the correct answer.
I rerun the generation of PDFs after a change in the system and compare to the stored and verified PDFs. Since my system always generates exactly the same PDFs for the same inputs.
Do you do the same? Or how does it happen, that for different executions you get PDFs that are in part moved slightly left or right?

**Comment by Corvwyn** [comment]
Ah yes. I do the same thing. Usually the only time the output changes is when I upgrade the render server (a paid product). That's what the test is mainly for, and right now we're doing a major upgrade after waiting a bit too long. 

We're also rendering from a lot of different formats, and we have to make sure the output doesn't change. At the moment I need to check about 70 files manually. Sometimes there are some very minor variation in some parts of the documents, like 1 mm or less I could ignore. That way I wouldn't have to manually go through the files.

**Comment by finsterwalder** [comment]
To tell you the truth: I will not work on this feature.
I don't need it and I don't see a lot of uses for it, either.

It's open source, feel free to work on it and create a pull request. :-)

Decide for yourself: Maybe you can somehow stabilize your tests, live with the manual checks or add the feature you need to PdfCompare yourself.

Sorry.

**Comment by Corvwyn** [comment]
No problem. Thanks for the advice. 

We don't upgrade that often, so I think I can manage without this feature, if not I'll see if I can implement something myself.
