### ISSUE TITLE
Inclusion points

### ISSUE THREAD

**Issue by zahid-1997** [red6/pdfcompare#121]
Hi , is it possible to include inclusion points as well with exclusion points.
For example lets say I have 3 paragraphs in my pdf and I want to compare the 2nd paragraph and if I give the co-Ordinates of 
2nd paragraph then it should show the difference in 2nd paragraph only.

**Comment by finsterwalder** [comment]
Unfortunately this is currently not possible.
You would have to create four exclusions: above, to the left, underneath and to the right of the 2nd paragraph to get what you need.
