### ISSUE TITLE
No pdf file found

### ISSUE THREAD

**Issue by soumyaevan** [red6/pdfcompare#14]
I am getting no file found error, though the path i have given consists of the required pdf file

**Comment by finsterwalder** [comment]
This is too little information for me to do anything.
I can't confirm, that files are not found.
How do you ensure, that the given path is correct and that Java finds your file under that path?
Where exactly does the error show? Do you have a stack trace?

**Comment by sharanyaj** [comment]
I get this error when I run man eclipse:eclipse
[ERROR] Duplicate classes found:
[ERROR] 
[ERROR]   Found in:
[ERROR]     org.slf4j:slf4j-log4j12:jar:1.6.1:runtime
[ERROR]     ch.qos.logback:logback-classic:jar:1.2.3:compile
[ERROR]   Duplicate classes:
[ERROR]     org/slf4j/impl/StaticMDCBinder.class
[ERROR]     org/slf4j/impl/StaticMarkerBinder.class
[ERROR]     org/slf4j/impl/StaticLoggerBinder.class

**Comment by finsterwalder** [comment]
Since you supplied no further information, I will close this issue now.
