### ISSUE TITLE
Resource leak: InputStreams are not closed 

### ISSUE THREAD

**Issue by S-Gaertner** [red6/pdfcompare#145]
`InputStream`s opened in the following lines of [`PdfComparator`](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java) are not closed anywhere:

- [127](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L127)
- [128](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L128)
- [154](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L154)
- [155](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L155)
- [181](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L181)
- [182](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L182)

Especially, the `RandomAccessReadBuffer`s in lines [392 ](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L392)and [393](https://github.com/red6/pdfcompare/blob/b8098a80d0c38982bf6fc4c6fb02a7aee0e5a15a/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L393), where those `InputStream`s are used, do not close their underlying `InputStream`s upon their own closure.

This can lead to resource leaks and file locking, depending on the platform-specific `InputStream` implementation. At some point in time the garbage collector will close the left over `InputStream`s, which can lead to undesirable behaviour due to its non-deterministic nature.

In case `InputStream`s are created internally in the library, they should be closed when not needed anymore. The only case where the `InputStream`s should not be closed is when they are created externally by the user and passed into the library using the `PdfComparator(final InputStream expectedPdfIS, final InputStream actualPdfIS)` constructor.

**Comment by finsterwalder** [comment]
Good catch!
I was under the assumption, that the RandomAccessReadBuffer would close the "underlying" inputStream.
Will change that.

**Comment by finsterwalder** [comment]
Version 1.2.1 is in the making.

**Comment by S-Gaertner** [comment]
Wow, that was quick! Thanks a lot 👍

**Comment by finsterwalder** [comment]
1.2.1 was released and should land in maven central within the next 1-2 hours.
With such a specific error description, it was easy to fix.

**Comment by S-Gaertner** [comment]
Unfortunately your fix does not work. I believe now you ask your `InputStreamSupplier`s to get yet another `InputStream` in lines 393 and 395, which you immediately close. However, the `InputStream`s you got in the immediately preceding lines are still not closed.

**Comment by finsterwalder** [comment]
You are right. I was too quick.
get() does not just "get" the stream, but actually creates it, since it's a Supplier.
Version 1.2.2 should fix it properly now. :-)
