### ISSUE TITLE
org/slf4j/LoggerFactory error when using pdfcompare with ivy.xml dependencies

### ISSUE THREAD

**Issue by heenavasdani1** [red6/pdfcompare#148]
Hi @finsterwalder , @rweisleder , @pSub , @SoltauFintel 

I'm experiencing an issue when using the pdfcompare library in my project. I have an ivy.xml file that contains the following dependencies:

`<dependency org="apache" name="commons-cli" rev="1.2" conf="release,dev->*" />
<dependency org="selenium" name="selenium" rev="3.7.0" conf="release,dev->*" />
<dependency org="testng" name="testng" rev="6.14" conf="release,dev->*" />
<dependency org="apache" name="log4j" rev="1.2.16" conf="release,dev->*" />
<dependency org="apache" name="freemarker" rev="2.3.28" conf="release,dev->*" />
<dependency org="jcommander" name="jcommander" rev="1.48" conf="release,dev->*" />
<dependency org="relevantcodes" name="extentreports" rev="2.41.2" conf="release,dev->*" />
<dependency org="rest-assured" name="restassured" rev="4.3.0" conf="release,dev->*" />
<dependency org="BeyondCompare" name="BCompare" rev="3.0.15.9758" conf="release,dev->*" />
<dependency org="poweradmin" name="psexec" rev="2.4.5" conf="release,dev->*" />
<dependency org="sqlite" name="sqlite-jdbc" rev="3.23.1" conf="release,dev->*" />
<dependency org="jna" name="jna" rev="5.8.0" conf="release,dev->*" />
<dependency org="eclipse" name="jaxb" rev="2.3.2" conf="release,dev->*" />
<dependency org="apache" name="pdfbox" rev="2.0.23" conf="release,dev->*" />
<dependency org="de.redsix" name="pdfcompare" rev="1.2.3" conf="release,dev->*" />
<dependency org="org.slf4j" name="slf4j-api" rev="2.0.16" conf="release,dev->*" />
<dependency org="ch.qos.logback" name="logback-classic" rev="1.5.12" conf="release,dev->*" />`

When I use the pdfcompare library in my Java tests, I'm getting the following error:
</div>org/slf4j/LoggerFactory

I've tried the following to resolve the issue:

Removing the log4j dependency
Excluding the slf4j-api artifact from the pdfcompare dependency
Cleaning and rebuilding the project

However, the issue persists. I suspect there might be a conflict between the SLF4J versions or implementations being used by the different dependencies.
Could you please provide any guidance on how to resolve this issue? I'm happy to provide more information or diagnostics if needed.
Thank you for your assistance!

**Comment by finsterwalder** [comment]
I can't really help you with ivy, unfortunately. 
As you can see in the pom.xml file of the project, PdfCompare depends on org.slf4j:slf4j-api:2.0.12
I don't even understand the "error": `org/slf4j/LoggerFactory`
Is that the only text, that is printed?
Nothing I can do, really...

**Comment by heenavasdani1** [comment]
@finsterwalder , Yes that is the only text that is printed when I am executing  the below line of code-
boolean isEqual = new PdfComparator(masterFilePath, testFilePath).compare().writeTo("result.pdf");

PdfCompare's classes calling org.slf4j.Logger internally so it is not able to find slf4j. I was getting that error, then only I tried to add slf4j as dependency externally. But when I am only installing this dependency-`<dependency org="de.redsix" name="pdfcompare" rev="1.2.3" conf="release,dev->*" />`  It should automatically installed all dependent dependencies but it is not happening and I was getting that error then I added slf4j explicitly but still it is not working. Is there any way to get more detail about error through pdfComparator?

Please help me to resolve it, as I tried many things but nothing worked.
Thanks!

**Comment by finsterwalder** [comment]
I really can't help much. Sorry.
Have you tried to use Maven as a build tool, just to see if that works or at least gives you more specific error messages?

**Comment by pSub** [comment]
@heenavasdani1 You could try to create a minimal, reproducible example. See for example https://stackoverflow.com/help/minimal-reproducible-example for a some tips on how to create one. This helps us reproduce the error and investigate it.

**Comment by heenavasdani1** [comment]
Hi @pSub  and @finsterwalder.

The project has many dependencies, and creating a similar structure for each would take considerable time. I attempted to trace the root cause of the issue and resolved the initial error. It turned out that the slf4j dependency wasn’t downloading correctly, causing it to be missing from the classpath. This missing dependency was the reason for the error.

However, even after fixing that, the pdfcompare library still isn’t working as expected. It’s throwing an exception, and when I debug the tests, I see this error in the compare method:
java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory

Could you help clarify in what cases we would expect this exception to occur?

**Comment by finsterwalder** [comment]
Comparisons do take some time.
But I can't see a reason, why a comparison via CLI would take considerable less time than when called in your own code. The default settings should be the same, unless you override any settings in your code.
PdfCompare is very memory hungry. If your code is using a lot of memory, maybe there is less memory left for PdfCompare, which can lead to a lot of GC. Maybe you could analyze GC behaviour of the two processes.

**Comment by finsterwalder** [comment]
That does not tell my anything. 😆 
The JVM has parameters to log GC activity.
Or you could use tools like jconsole or visualvm

**Comment by heenavasdani1** [comment]
@finsterwalder , What about this?
![image](https://github.com/user-attachments/assets/5f447ba7-ec4e-4baf-ad4b-4eeda82425ee)

**Comment by heenavasdani1** [comment]
@finsterwalder ,
Is the time really spend inside PdfCompare exclusively?-yes
Is the comparison completed successfully?-yes
I reduced the DPI value and also used the new CompareResultWithMemoryOverflow() feature, it is working fine now. Thanks!

Could you please tell me to get an 80% accuracy result what value of DPI should I set? Currently, I set DPI-150.

Also, I noticed when I am using PDF Compare UI, that it got stuck while opening attached pdfs.
[H2HRowsImppJobResubmitMaster_Master.pdf](https://github.com/user-attachments/files/17727830/H2HRowsImppJobResubmitMaster_Master.pdf)
[Head to Head Rows _rAlF_1_New.pdf](https://github.com/user-attachments/files/17727832/Head.to.Head.Rows._rAlF_1_New.pdf)

**Comment by finsterwalder** [comment]
I don't understand what you mean with 80% accuracy.
DPI is mainly a tradeoff between speed, memory and the level of details you are able to find.
150 DPI may be a good tradeoff for you.

**Comment by heenavasdani1** [comment]
Dependencies issues, Fixed it, everything is working fine now.
