### ISSUE TITLE
compile time error for ch.qos.logback:logback-classic:jar:1.2.3

### ISSUE THREAD

**Issue by sharanyaj** [red6/pdfcompare#15]
I get this error when I run mvn eclipse:eclipse
[ERROR] Duplicate classes found:
[ERROR]
[ERROR] Found in:
[ERROR] org.slf4j:slf4j-log4j12:jar:1.6.1:runtime
[ERROR] ch.qos.logback:logback-classic:jar:1.2.3:compile
[ERROR] Duplicate classes:
[ERROR] org/slf4j/impl/StaticMDCBinder.class
[ERROR] org/slf4j/impl/StaticMarkerBinder.class
[ERROR] org/slf4j/impl/StaticLoggerBinder.class

There is compile time error for ch.qos.logback:logback-classic:jar:1.2.3
If I exclude this jar, there is no error. But I'm not sure if its the right way

**Comment by finsterwalder** [comment]
slf4j-log4j12.jar is not part of PdfCompare, but of your own build, so this is not really a PdfCompare problem.

I think, slf4j-log4j12.jar and logback-classic.jar are competing logging backends and should not be on the classpath at the same time. Either you log with the logback backend or with the log4j bridge.
I think you need to exclude the logback-classic backend, if you want to use the log4j bridge.
Please read the slf4j docs, to be sure.
