### ISSUE TITLE
I'm compare two same files but got [Diff-3-thread-1] INFO de.redsix.pdfcompare.DiffImage - Differences found at { page: 1, x1: 424, y1: 863, x2: 2356, y2: 1817 }

### ISSUE THREAD

**Issue by Alexandr-Kaliuk** [red6/pdfcompare#21]
Hi, I'm try two compare downloaded file with goldenCopy (they are the same), but on finish I am got message that "differences found". 
Assumption: When I'm compare files locally - all is fine. Problems starts when I'm get goldenCopy from gitHub and compare it with same file downloaded from browser. 
![image](https://user-images.githubusercontent.com/22213086/40363700-ff79415c-5dd8-11e8-8c7a-96829a5119da.png)

Maybe You know how I can get around this problem?
Thank You!

**Comment by finsterwalder** [comment]
Hi Alexandr,

I'm not sure I understand your problem.
I don't quite understand what you mean with "goldenCopy".
The image you posted looks very different to me, so I would expect a diff. The font is different.
PdfCompare renders each Page of your Pdf as an image and compares them pixel by pixel.
If you really habe identical Pdfs, I don't see how that gives a diff.
If your Pdfs are somehow different (use different fonts but show the same content), that gives a diff, of course.
PdfCompare does not read the text and compares that.

**Comment by Alexandr-Kaliuk** [comment]
I understand. Ok, thank You for quick reaction!
