### ISSUE TITLE
is there a way to exclude the differences of the actual data between two PDF reports?

### ISSUE THREAD

**Issue by aeendale** [red6/pdfcompare#22]
I am trying to compare two PDF reports irrelevant of the actual data. I am more interested to ensure the coordinates of the data between the two reports are identical. is there a way to exclude the difference of data between two PDF reports using the pdfCompare library?

**Comment by finsterwalder** [comment]
You can define areas of your document, that should be excluded from the comparison.
Check out exclusions in the README.
Some Background: PdfCompare renders PDF pages to images and does a pixel by pixel compare. All you can do is exclude rectangular areas from the comparison.
