### ISSUE TITLE
Defining allowed difference

### ISSUE THREAD

**Issue by keisar** [red6/pdfcompare#23]
Hi,
We've started using pdfcompare recently for testing our templating service and it works great!
One issue we're facing is that the generated PDFs from our local machines (OSX) are different from what is generated on our servers, the difference is very small (0.1% difference) but still they are not equal and so out tests fail.
I was thinking of contributing a way of defining the allowed difference, I started going over the code and thought maybe you'll have ideas or leads on how to implement.

**Comment by finsterwalder** [comment]
Hello Keisar,

thanks for offering your help in improving PdfCompare!

I started writing to you about my ideas, how this feature could be incorporated.
In the end I couldn't think it through without coding it, so I did (doing a little refactoring along the way). At least I coded a feature that allows you to configure via a config file the percentage of pixels that may differ.

A new version was just released. It usually takes a little while until it shows up in maven central.
The new readme describing the feature is already on github.

Check it out and see if that's what you need.
If not, feel free to further improve on it!
