### ISSUE TITLE
SLF4J Errors

### ISSUE THREAD

**Issue by chisasaw** [red6/pdfcompare#26]
I am using the pdfcompare library to compare two pdf documents. However, I got the following error: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". I included the slf4j api to my class path when compiling and running my code but I am still getting the same error. How can this be resolved?

**Comment by finsterwalder** [comment]
The class in question is not part of the slf4j api, but of the logback-classic logging backend.
It should be pulled as a transitive dependency. Do you use maven to build your project?

I have the following dependencies in my project:
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>

**Comment by chisasaw** [comment]
Thank you. I resolved the error.
