### ISSUE TITLE
Add exclusions via API and without config file

### ISSUE THREAD

**Issue by rweisleder** [red6/pdfcompare#31]
Currently it is necessary to create a config file to define exclusions. It would be useful to add exclusions directly without a config file.

Example:
```
// ignores a single page
withIgnore(int page)

// ignores an area on all pages
withIgnore(String x1, String y1, String x2, String y2)

// ignores an area on a single page
withIgnore(int page, String x1, String y1, String x2, String y2)
```

Should it be named "withIgnore" or "withExclusion"?

**Comment by Ebsy** [comment]
In which situations would this be useful? Genuine question.
The config file makes it much more flexible to define exclusions rather than having it 'hard coded'.

**Comment by rweisleder** [comment]
We have a use case where the user wants to compare files from the production system with files from a stage system. So they define some information like
* conditions on how to find matching files in both systems
* the allowed difference (see #32)
* the exclusions

Those data are stored in and read from a file or a database into domain objects. So it would be easier to write (and maintain) method calls against an API instead of depending on a file-based API.

Yes, the current apporach is very flexible. But with the above use case I have to convert my domain object into a config file, call `withIgnore(InputStream)` and let pdfcompare parse the file again.

**Comment by finsterwalder** [comment]
Makes sense...
It shouldn't be such a big deal to add such a feature.
But I don't have a lot of time for the project at the moment...
Maybe you can take a look at the project and see, whether you can create a pull request?

**Comment by rweisleder** [comment]
> It shouldn't be such a big deal to add such a feature.

I'll work on this one on the next days.

**Comment by finsterwalder** [comment]
Version 1.1.33 contains the feature and should land in maven central during the next couple of hours.
