### ISSUE TITLE
Add API method to set the allowed difference

### ISSUE THREAD

**Issue by rweisleder** [red6/pdfcompare#32]
In a single run I want to compare multiple PDF files. Each file has a different "allowed difference". Currently it is only possible to set a global "allowed difference" via the application.conf. It should be possible to configure it per run.

**Comment by Ebsy** [comment]
I agree on this one. It'd be useful to define a difference tolerance per run.

**Comment by hsoehalim** [comment]
I'm curious, how do we create Environment obj. There's no default public constructor for this class (it's set to private). Are we suppose to provide our own implementation of Environment class?

Thanks,
Harry

**Comment by rweisleder** [comment]
Currently, there is no possibility to create an `Environment` object. It's only possible to configure the `Environment` with a config file.

With my proposed PR the `Environment` is an interface. There are possibilities to use the "old" default with a config file, provide a configuration with a POJO, or provide a custom implementation of this interface.

**Comment by danile42** [comment]
That's a cool feature! I'll try to create a PR to have in the main documentation page.
