### ISSUE TITLE
If i compare two PDF with 139 pages, diffOutput PDf is not generated 

### ISSUE THREAD

**Issue by venkywarriors619** [red6/pdfcompare#35]
PDF which i have used is attached
[document (3).pdf](https://github.com/red6/pdfcompare/files/2230603/document.3.pdf)
using Pdfcompare version 1.1.33 & PDFbox 2.0.11, 
i have two questions 
what is the limit for the pages that can compare?
what is limit for PDF size?

**Comment by finsterwalder** [comment]
I close this issue now, since there was no further request.
Should you need further help, don't hesitate to reopen the ticket.
