### ISSUE TITLE
Compare with password protected PDF file

### ISSUE THREAD

**Issue by paulfkp** [red6/pdfcompare#39]
I found this pdf comparator so awesome and really helpful for my project testing, but recently I have a problem with the password protected file, Is it possible to add a method in to insert the password so the file become unprotected?

**Comment by finsterwalder** [comment]
The new release has support for encrypted PDFs through PdfComparator.withExpectedPassword() and PdfComparator.withActualPassword() methods.

**Comment by paulfkp** [comment]
Appreciated for your work! Thanks
