### ISSUE TITLE
Use specific configuration file OR prefix configuration entries with e.g. "pdfcompare"

### ISSUE THREAD

**Issue by danile42** [red6/pdfcompare#40]
Since pdfcompare uses the default configuration file name "application.conf", it will probably share this file with other libraries that also use Typesafe config. To avoid confusion, pdfcompare should either use a custom file (e.g. "pdfcompare.conf"), or add prefixes to its property keys (e.g. "pdfcompare.allowedDifferenceInPercentPerPage"). Typesafe config allows easy handling of such namespacing prefixes.

**Comment by finsterwalder** [comment]
Hi Danile,

thanks for the hint. I didn't think about that.
I would prefer a different file name over prefixes, since prefixes would make the entries very long.
I will look into that...

**Comment by finsterwalder** [comment]
I will probably not change this, since noone reported a real problem.
It's very unlikely, that there will be actual collisions between keys.

**Comment by finsterwalder** [comment]
A different configuration file can be provided via command line arguments (see README) or via a custom ConfigFileEnvironment.
