### ISSUE TITLE
Option to find if differences are ONLY in Excluded Areas

### ISSUE THREAD

**Issue by AnuradhaThulasidoss** [red6/pdfcompare#41]
Hi,
I would like to report the test as PASS if differences are there BUT ONLY in Excluded Areas.
Please let me know if there is a way to achieve this currently.
If not please guide me to customize the library or suggest a workaround.
Any help would be great !

Regards
Anuradha

**Comment by finsterwalder** [comment]
Differences in Excluded Areas are actually ignored. So they are reported as passing.
CompareResult has an isEqual() Method, which returns true, when differences are only in excluded areas. There is another method hasDifferenceInExclusion(), which reports Differences in excluded areas.

So you must do something else wrong, I suppose.
Did you try the writeTo(...) method and look at the resulting difference Pdf?
Or could you give more information on what you do?
