### ISSUE TITLE
Implementation of DiskUsingCompareResult is missing

### ISSUE THREAD

**Issue by bruecp** [red6/pdfcompare#48]
Hi, 
in the readme.md the possibility of using the DiskUsingCompareResult ist mentioned, which comes into play in memory comsumption issues.
Unfortanutelly, this class is not available in the current master distribution.

Can you please re-provide this CompareResult Strategie back again, as it is very useful when memory comsumption is an issue.

Thanks & BR,
Peter

**Comment by finsterwalder** [comment]
I updated the README.
There are two CompareResults, that store to disk now:
CompareResultWithPageOverflow and CompareResultWithMemoryOverflow.
The old DiskUsingCompareResult no longer exists.
