### ISSUE TITLE
Challenging Compare

### ISSUE THREAD

**Issue by bruecp** [red6/pdfcompare#49]
Hi, 
in my use case I have to compare two very larege PDF documents.
Each of them have around 610 MBs and consists of more than 14.800 pages.
![challenging pdf sizes and pages](https://user-images.githubusercontent.com/45709679/51315901-8fe0e880-1a53-11e9-834d-26530b8dd642.PNG)

I tried all available CompareResult Strategies, whereas the 
CompareResultWithPageOverflow (with 50 or 100) pages, was progressing at best.
Unfortuantelly, not even one strategie finished the job. 
Even the Overflow Strategies raised java heap space exceptions and stocked in the end.

I also tunes the library through the application.conf as follows:
imageCacheSizeCount=30
maxImageSizeInCache=100000
mergeCacheSizeMB=100
swapCacheSizeMB=100
documentCacheSizeMB=200
parallelProcessing=true
overallTimeoutInMinutes=3

Finally (with CompareResultWithPageOverflow) some partial.pdfs are stored in my %APPDATA%/local/Temp directory, but the application does not response anymore.

So what are your suggestions to meet this challenge?
What may I provide you further, except I am not allowed to give you these large PDF files, as of data governance restrictions (beside the large amount).

Here are some code snippets for my usage:
...
   public static void main(String[] args) {

        SpringApplication.run(PdfcompareTestApplication.class, args);

        if (args != null && args.length > 0)
            parseArguments(args);

        try {
            executeCompare();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

private static void executeCompare() throws IOException, InterruptedException {

        CompareResult result = null;

        System.out.println("Start test with following settings: ");
        System.out.println("==========================================================================");
        System.out.println("    f1 : " + file1  + " <--> " + "  f2 : " + file2);
        System.out.println("    mode : " + mode);
        System.out.println("    loops : " + loops);
        System.out.println("    writeDiff : " + writeDiffs);
        System.out.println("    printMemory: " + printMemory);
        System.out.println("==========================================================================");

        Instant start = Instant.now();
        for (int i = 0; i < loops; i++) {
            Instant startLoop = Instant.now();
            if (mode == 3) {
                result = executeCompareResultWithPageOverflow();
            }
            else if (mode == 2)
            {
                result = executeCompareResultWithMemoryOverflow();
            }

            else
                result = executeCompareResult(null);

            Instant endLoop = Instant.now();
            System.out.println("Duration of loop " + i + ": " + Duration.between(startLoop, endLoop).toMillis() + "ms. # of Pages: " + (result.getNumberOfPages() + 1) + ". Differences: " + (result.isNotEqual() ? "yes" : "no"));
            if (result.isNotEqual() && writeDiffs) {
                result.writeTo("diff");
                System.out.println("Wrote ./diff.pdf");
            }

            result = null;

            if (printMemory)
                printMemory("intermediate");
       }

        Instant end = Instant.now();
        System.out.println("Total duration: " + Duration.between(start, end).toMillis() + "ms");

        if (printMemory)
            printMemory("finished");

        System.exit(0);
    }

   private static CompareResult executeCompareResultWithPageOverflow () throws IOException {
        CompareResult result = new CompareResultWithPageOverflow(50);
        return executeCompareResult(result);
    }

    private static CompareResult executeCompareResultWithMemoryOverflow () throws IOException
    {
        CompareResult result = new CompareResultWithMemoryOverflow();
        return executeCompareResult(result);
    }

    private static CompareResult executeCompareResult (CompareResult result) throws IOException
    {
        if (result != null)
            return new PdfComparator(file1, file2, result).compare();
        else
            return new PdfComparator(file1, file2).compare();
    }
...

Many thanks and BR,
Peter

**Comment by finsterwalder** [comment]
Hi Peter,

difficult to say from here... But I understand, that you can't give me your documents.

How much heap do you give your JVM?
When you have memory problems, you could try to analyze them with a Memory Analyzer like https://www.eclipse.org/mat.
I would try a PageOverflow with fewer Pages (e.g. 5 or 10).
Increase the JVM Heap size?
Maybe you also need to do some GC tuning?!

I start my App with the following Settings:
 java -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/logs/gc.log -Xms2G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/logs my.jar

And I use a CompareResultWithPageOverflow(5).

So 2G heap and 5 pages works for me. More heap, more pages... roughly...

Greetings,
   Malte

**Comment by finsterwalder** [comment]
I'm usind JDK 1.8.0_172

**Comment by bruecp** [comment]
Hi Malte,
thanks for your fast reply. 
I will try to play with the recommended settings.

Should I use parallel processing (which is currently enabled)?
Would you tune the application.conf settings?

In attach, you can find the my log, whereas the last lines written are during CTRL-C (about the programm).

The currently used JVM settings are:
"java -jar -Xms8G -Xmx16G pdfcompare-test-1.0.0.jar -mode 3 -loops 1 -printMemory true -writeDiff true -f1 NICHT_DRUCKEN_ORIG_239330.pdf -f2 NICHT_DRUCKEN_239330.pdf > log.txt
pause"

Thank you & BR,
[log.txt](https://github.com/red6/pdfcompare/files/2768526/log.txt)

Peter

**Comment by finsterwalder** [comment]
Maybe your system running a Virus Scanner, that interferes with the temp files?

I didn't change the application.conf

Reduce the number of pages in your CompareResultWithPageOverflow to 10 and see what happens.

**Comment by finsterwalder** [comment]
I use 2GB and 5 Pages Overflow. That works for me.
When I said to use 10 Pages, I meant to only reduce the pages and keep the Heap size you had.
2GB and 10 Pages will most likely not work. Your 8 to 16GB might work with 20-30 Pages the most, scaling up from my experience. But maybe less.
I would start out with 10 pages to see if you get it to work in the first place. Or go even lower. Once it works, you can start to tune it up to find a good balance between memory and performance.
PdfCompare uses a lot of memory per page.

**Comment by bruecp** [comment]
Hi Malte,
I have now tried several combinations. 
I also changed the machine to execute the tests on an linux system, to be sure there are no virus scanning problems. This machine newer raised out of memory / java heap space errors, as it had 20 GB to it's rescue. The java process simple changed to a sleeping (process status S) state, waiting for some event.

I then reduced the maxPage Size to 1 and used up to 12G heap size on my windows maching.
So I also got no out of memory / java heap space errors. In the process resource monitor you can see (see attachment) that one thread of the same process is waiting on some other, even I don't use paralleProcessing.

How to check this further? 

Thank you for your help.
BR,
Peter

![challenging pdf sizes and pages 2](https://user-images.githubusercontent.com/45709679/51332798-b2d3c280-1a7c-11e9-8400-c46731f1442b.PNG)

**Comment by finsterwalder** [comment]
Interesting...
I actually never use the single threaded mode. ;-) Maybe try parallel and
see what happens.
I don't have time to look into this any further right now. Maybe next week.

Greetings,
   Malte

Am Do., 17. Jan. 2019, 17:24 hat bruecp <notifications@github.com>
geschrieben:

**Comment by bruecp** [comment]
Hi Malte,
thanks. I tried both modes via the application.conf file:

imageCacheSizeCount=30
maxImageSizeInCache=100000
mergeCacheSizeMB=100
swapCacheSizeMB=100
documentCacheSizeMB=200
parallelProcessing=true
overallTimeoutInMinutes=15
allowedDifferenceInPercentPerPage=0

Is there a possibility, to print out if those settings are really active?

Next week sounds great. 
Meanwhile, I will try to organize a smaller test dataset, which I am allowed to share with you.

Many thanks for your fast support!
BR,
Peter

**Comment by bruecp** [comment]
Hi Malte,
could you spend already some time in my issue this week?

In my opinion, it seems that the CompareResultWithPageOverflow strategy has some threading problem, during writting to disk and processing the compare. This happens, even the parallelProcessing ist set to false (when I did it correctly see Screenshot).

I ask my colleages to provide me a test dataset with less amound of size and pages and I will try to present you with an test case, but I would please you to cross-check your design and code, whether you have a clue, how it could come to this situation.
Event when the PDF document is wrong or uses some bad fonts or styles, your library should not crash or run into a dead-lock.

Thanks and best regards,
Peter

![application conf](https://user-images.githubusercontent.com/45709679/51683785-ec5f7d00-1fea-11e9-899d-bf48295a8769.PNG)

**Comment by bruecp** [comment]
Hi Malte, 
today, I got a PDF which I can give you for further investigations.

I tried all three strategies:

- CompareResult runs out of memory
- CompareResultWithPageOverflow und CompareResultWithMemoryOverflow ends up in a dead lock.

Can you please try to compare this PDF document (duplicate it for actual and expected) with one of the Overflow-Strategies and tell me my usage mistake or your bug.

I also can give you my test project, if you like.

Thanks and BR,
Peter

[out_000003_01.pdf](https://github.com/red6/pdfcompare/files/2808198/out_000003_01.pdf)

**Comment by finsterwalder** [comment]
Great! Thanks for the document.
It does produce a deadlock in parallel processing mode. This happens during swapping, but I couldn't quickly figure out, what exactly is causing the problem. I'll have to look into that.

Without parallel processing (application.conf: parallelProcessing=false), the compare worked for me, though.

**Comment by bruecp** [comment]
Hi Malte,
as I tried both application.conf (parallelProcessing=false and application.conf: parallelProcessing=true), how  to get sure, this config file gets even used?
Is there a verbose flag to see which settings are there.

I placed the application.conf file hiere 
![application conf](https://user-images.githubusercontent.com/45709679/51923350-1057ff80-23eb-11e9-89e6-1f6823f2d034.PNG)

Thanks & BR,
Peter

**Comment by finsterwalder** [comment]
Sorry. I don't log a whole lot. :-)
The application.conf needs to be on the classpath. Put it in the resources folder for that.

**Comment by bruecp** [comment]
Hi Malte,
next challenge. 
When I run the test now, with parallelProcessing=false, it seems working, until I call CompareResult.getNumberOfPages, which forces an InvocationTargetException.

For my evaluation I don't need this method really, but why a call of it raises an exception?

Thanks & BR,
Peter

My command line: 

c:\Temp\pdf>java -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/logs/gc.log
 -Xms2G -Xmx6G -XX:+AggressiveHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpP
ath=/logs -Djava.io.tmpdir=/Entwicklung/temp/ -jar pdfcompare-test-1.0.2.jar -mo
de 3 -maxPages 10 -loops 1 -printMemory true -writeDiff true -f1 out_000003_01ex
pected.pdf -f2 out_000003_01actual.pdf

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.1.RELEASE)

2019-01-30 09:23:01.994  INFO 8200 --- [           main] a.g.b.j.a.p.PdfcompareT
estApplication    : Starting PdfcompareTestApplication v1.0.2 on PC91941 with PI
D 8200 (C:\Temp\pdf\pdfcompare-test-1.0.2.jar started by BRUECKLPE in c:\Temp\pd
f)
2019-01-30 09:23:01.994  INFO 8200 --- [           main] a.g.b.j.a.p.PdfcompareT
estApplication    : No active profile set, falling back to default profiles: def
ault
2019-01-30 09:23:02.743  INFO 8200 --- [           main] a.g.b.j.a.p.PdfcompareT
estApplication    : Started PdfcompareTestApplication in 1.139 seconds (JVM runn
ing for 2.201)
Start test with following settings:
==========================================================================
    f1 : out_000003_01expected.pdf <-->   f2 : out_000003_01actual.pdf
    mode : 3
    loops : 1
    writeDiff : true
    printMemory: true
    maxPages (only used with mode 3): 10
==========================================================================
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Caused by: java.util.NoSuchElementException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
        at java.util.TreeMap$KeyIterator.next(Unknown Source)
        at java.util.Collections.max(Unknown Source)
        at de.redsix.pdfcompare.CompareResult.getNumberOfPages(CompareResult.jav
a:146)
        at at.gv.brz.justiz3.architecture.pdfcomparetest.PdfcompareTestApplicati
on.executeCompare(PdfcompareTestApplication.java:132)
        at at.gv.brz.justiz3.architecture.pdfcomparetest.PdfcompareTestApplicati
on.main(PdfcompareTestApplication.java:35)
        ... 8 more

c:\Temp\pdf>

**Comment by bruecp** [comment]
Hi Malte,
some weeks passed by. Are there any news from your side about which bugs you will fix and what's your roadmap?
Tomorrow, we have our next technical decision meeting, where we will discuss the usage of your library.
The current version we cannot use in a productive environment, as of the mentioned bugs.

Thanks & BR,
Peter

**Comment by finsterwalder** [comment]
It is a side project for me.
The library does work for you, if you run in single threaded mode?
And don't use the broken getNumberOfPages?
I didn't yet find the time to look into the threading issue and can't promise any timeline.
But you are free to investigate yourself. ;-) It's OpenSource after all...

**Comment by Lonzak** [comment]
Hi bruecp - this is an open source project and you have access to the sourcecode. So jump in and help fixing the bugs you found. Afterwards provide them to the comunity.

**Comment by finsterwalder** [comment]
I fixed the getNumberOfPages problem.
That should work in all cases now.
But that is just a side-problem anyways...

**Comment by cnatesan** [comment]
Hello Malte,

This is wonderful and so far works great. I just  have a question regarding how the differences are shown now like overlapping each other. Is there a way that we can have the differing things one below other or just have only one value(actual) with the color highlighting to indicate its different

**Comment by finsterwalder** [comment]
I know it's been a while, but I noticed, that the compare now works in multithreading mode as well.
I can't say why exactly, but obviously the bug has been solved... :smiley:
