### ISSUE TITLE
exclude header and footer  x1,y1.....x3, y3  x4, y4  

### ISSUE THREAD

**Issue by bbrtan** [red6/pdfcompare#56]
HI,  

Firstly thanks for the library. as many said it helps alot.

Ive read this https://github.com/red6/pdfcompare/issues/46 which is closed. 

i have manage to excluded the header region. 

how do i add a 2nd exclude for the footer region?

this for my header for every page:

exclusions: [
    {
        x1: 0 
        y1: 0
        x2: 2000
        y2: 468
    },
]

how is the excluded footer defined?  x3 , y3 ....  ??

again thanks for the advice.

Update:

would it be like this?

#############
exclusions: [
    {    //header for all pages
        x1: 0 
        y1: 0
        x2: 2000
        y2: 468
    },
	{    //footer for all pages
        x1: 0 
        y1: 2620
        x2: 1980
        y2: 2800
    },
	
]

#############

**Comment by finsterwalder** [comment]
Yes, exactly. Just try it and look at the resulting Difference-PDF. You will see ignored regions in yellow.
