### ISSUE TITLE
Support encrypted PDF file in the UI

### ISSUE THREAD

**Issue by qq57941500** [red6/pdfcompare#58]
Thanks a lot for the wonderful library!
I feel the UI screen is very handy to compare two files. However it does not support encrypted PDF file.
Please consider to fix it when you find time:)

**Comment by tpiekarski** [comment]
I'd like to take a look into that at this weekend, I'm curious about how to handle encrypted PDFs.

**Comment by qq57941500** [comment]
> When solving this issue did not start, and in general it is a feature which should be added I'd like to take a look into that. I'm curious about how to handle encrypted PDFs. :)

Should not be hard to fix since it has the API to support encrypted PDF, only missed in the UI part.
Looking forward to seeing the new version :)
