### ISSUE TITLE
Utility fails to create complete result for large size pdf files.

### ISSUE THREAD

**Issue by prashantpahwa** [red6/pdfcompare#60]
On comparing a PDF with size 1800 pages, It chokes up the CPU and 12 GB of RAM for 15 minutes. The result varies with 75-150 pages instead of 1800 pages.

**Comment by finsterwalder** [comment]
In this general form it is really hard to tackle this problem.
Would it be possible that you supply one of your documents? Or a generated document that shows the problem?

**Comment by finsterwalder** [comment]
Since there was no reaction, I close this ticket for now.
Feel free to contact me for further investigation...

**Comment by Lonzak** [comment]
@prashantpahwa Can you supply a test document? Provide some details...
