### ISSUE TITLE
Feature: Colourblind mode

### ISSUE THREAD

**Issue by pensionarchitects-ben** [red6/pdfcompare#62]
Hi,

First of all thanks for the library.
We currently use this for testing our pdf files. Although I can see the differences perfectly, I have a colleague who is colourblind  (red-green) and for him the differences are harder to see. Is there a feature planned for the colourblind under us, or can you point me to where the colours are set so I can create a pull request with configurable colours.

Thanks in advance
Ben Maes

**Comment by finsterwalder** [comment]
Great idea.
I created a new version that allows you to define the colors in the application.conf file.
See the new README for more details.

**Comment by finsterwalder** [comment]
Check for version 1.1.42

**Comment by finsterwalder** [comment]
Version 1.1.42 could not be release, due to a PGP Signature Failure.
Please look for version 1.1.43 instead.

**Comment by pensionarchitects-ben** [comment]
Thanks for adding this so quick
