### ISSUE TITLE
withIgnore(new pageArea()) can not be resolved

### ISSUE THREAD

**Issue by apathan123** [red6/pdfcompare#63]
Hi I am tryign to use withIgnore function but teh code is not gettign compiled.
boolean isEquals = new PdfComparator(ref, act).withIgnore(new PageArea(1, 1600, 2210, 2200,2300)).compare().writeTo(diffPath);
Error in eclipse code:
The method withIgnore(String) in the type PdfComparator is not applicable for the arguments (PageArea)

Can you pelase help me resolve this one

**Comment by finsterwalder** [comment]
That's strange.
Do you use the current version of PdfCompare?
When you look at source code for the class IntegrationTest you will find an example just like that.

**Comment by finsterwalder** [comment]
Could you attach a complete Sourcefile, that shows the problem?

**Comment by apathan123** [comment]
Can not put teh source code as its part of libary file I have created and is huge: Here is the fucntions which is using PdfComparator:
protected boolean PDFCompare(String resultPath, String refPath) throws IOException {

		String ref = refPath;
		String act = resultPath;

		String diffPath = "/tmp/devRFB_Diff";
		

		@SuppressWarnings("rawtypes")
		boolean isEquals = new PdfComparator(new File(ref),new File(act)).withIgnore(new PageArea(1,1600, 2221, 2200,2300)).compare()
				.writeTo(diffPath);
		logger.info("Differece saved @ location: " + diffPath + "...............");
		System.out.println("Differece saved @ location: " + diffPath + "...............");

		if (!isEquals) {
			
			System.out.println("Differences found!");
		} else {
			logger.info("\nPDFs are same");
		}

		return isEquals;
	}
Error screenshot at this line:
![image](https://user-images.githubusercontent.com/32069580/72958043-c9b59f00-3dcb-11ea-9562-30564d1a50c1.png)

**Comment by finsterwalder** [comment]
Did you check your dependencies with mvn dependency:tree?
Did you jump to the source of withIgnore() and check that file?
Can you create a new project with a stripped down pom file and a single class that calls PdfCompare?

**Comment by finsterwalder** [comment]
Your code compiles fine, when I paste it into my project. I'm pretty sure there must be something wrong with your project setup.
And just some basics: Did you run a mvn clean compile? Did you restart Eclipse and Rebuilt the project in Eclipse and things like that? Since Eclipse sometimes messes up too...

**Comment by apathan123** [comment]
Yes. Somethign starnge. I created new project and it compiled fine without any issues . So no point in sharing. 
In my existing code I dont see withIgnore(Page Area) argument function available with PDFCompare.. 
Yes I did mvn clean install from comand prompt still doesnt work :(
what next?

**Comment by finsterwalder** [comment]
I still have the hunch, that somehow the wrong version of PdfCompare is used. Older versions didn't have the withIgnore(PageArea) method.
When you navigate to the source of the withIgnore method, which library in which version is it in? Eclipse shows you that.
Or maybe completely remove pdfcompare from your local maven repo and do a clean build again? With "rm -rf ~/.m2/repository/de/redsix" (on a Unix system) I don't know from the top of my head where the local maven repo is stored on Windows, should you use a windows system...

**Comment by apathan123** [comment]
That did teh trick!! Deleted redsix from C:\Users\username\.m2\repository\de and did clean istall and error is gone! Thanks So much for your swift response!!!

**Comment by finsterwalder** [comment]
Glad I could help. :-)
