### ISSUE TITLE
Allow for a difference in percent per page via API

### ISSUE THREAD

**Issue by rsilva2** [red6/pdfcompare#64]
Any way we can set this difference in percentage via the API, I have JUnit tests and would like some pdfs to allow different percentages.  

Also having a hard time figuring out gradle to allow the application.conf file to be added to the build from the test sources folder to be used in my unit tests, any help on that would be great, but just being able to set the percentage difference through code would solve my issue. Thanks.

**Comment by finsterwalder** [comment]
You can do that with:
Environment env = new SimpleEnvironment();
env.setAllowedDiffInPercent(5.0);
new PdfComparator(...).setEnvironment(env).compare()

application.conf needs to be on the classpath root. Anything that is on the classpath will do. src/test/resources/application.conf should work.

**Comment by finsterwalder** [comment]
Actually I will rename setEnvironment to withEnvironment, so setEnvironment will be deprecated.

**Comment by finsterwalder** [comment]
Please use version 1.1.44 and see the updated README.md for usage.

**Comment by rsilva2** [comment]
thanks it's working great.
