### ISSUE TITLE
Encoding issue 

### ISSUE THREAD

**Issue by rsilva2** [red6/pdfcompare#65]
When i switched from version 1.1.40 to 1.1.44  i'm getting encoding errors, text that used to work fine are now garbled.  I'm using a report in french.

for example 
![image](https://user-images.githubusercontent.com/3476616/73405086-4e168f00-42b0-11ea-99a5-a8ad2e9a2e8c.png)

appears when it should be 
![image](https://user-images.githubusercontent.com/3476616/73405104-58d12400-42b0-11ea-8b12-b95dbbc11f72.png)

**Comment by finsterwalder** [comment]
Interesting. At first glance that looks like a problem in PdfBox. (The library that is used to read and render the PDF documents. We upgraded from 2.0.15 to 2.0.18.
Could you check out the current version of PdfCompare from Github, replace the PdfBox version 2.0.18 with version 2.0.15 in the pom.xml and try that locally?

**Comment by finsterwalder** [comment]
Or alternatively give me a PDF file that shows the problem?

**Comment by rsilva2** [comment]
Hello sorry i was busy yesterday. I checked out the project and changed the pdfbox version to 2.0.15 and can confirm that it now works correctly.

**Comment by finsterwalder** [comment]
Maybe you could file a ticket for PdfBox? And send them a Pdf that shows the problem?
https://issues.apache.org/jira/projects/PDFBOX

**Comment by finsterwalder** [comment]
Since it's a problem in PdfBox I will close this ticket here...
@rsilva2 Did you file a bug with PdfBox? Could you add a link to it here?
