### ISSUE TITLE
Allow custom DPI in the settings

### ISSUE THREAD

**Issue by pec0ra** [red6/pdfcompare#66]
Currently, the DPI of the comparison images is fixed at 300. It would be good to have an option in the settings (`application.conf` and Java API) to change it to other values.

**Comment by finsterwalder** [comment]
Good idea. I will add that soon.

**Comment by finsterwalder** [comment]
I just created version 1.1.45, which allows to set DPI through the environment.
May take a few hours, until the version shows up in maven central (as always).
This also brings along the change, that withEnvironment(...) needs to be called before any withIgnore(...) method calls.
