### ISSUE TITLE
Unable to use setAllowedDiffInPercent() 

### ISSUE THREAD

**Issue by apathan123** [red6/pdfcompare#67]
I have following code where I am trying to set alloweddiffin percent. But the code does not get compiled and shows error at Compare() saying "Cannot invoke compare() on the primitive type void" Please help me understand what is wrong in the code.
SimpleEnvironment e= new SimpleEnvironment();
		e.setAllowedDiffInPercent(0.2);
		boolean isEquals = new PdfComparator(ref, act)
				.withIgnore(new PageArea(1, 1600, 2000, 2400, 2300))
				.withIgnore(new PageArea(2, 1, 3900, 400))
				.setEnvironment(e)
				.compare()
				.writeTo(diffPath);

**Comment by finsterwalder** [comment]
setEnvironment() is deprecated. Use withEnvironment() instead.
withEnvironment() should also be the first call.
setEnvironment() does not return a value.

**Comment by apathan123** [comment]
Please dont rush to close the issue. 
I had tried with withEnvironment and this is the error I get "The method withEnvironment(SimpleEnvironment) is undefined for the type PdfComparator"
SimpleEnvironment e= new SimpleEnvironment();
		e.setAllowedDiffInPercent(0.2);
		boolean isEquals = new PdfComparator(ref, act).withEnvironment(e)
				.withIgnore(new PageArea(1, 1600, 2000, 2400, 2300))
				.withIgnore(new PageArea(2, 1, 3900, 400))
				.compare()
				.writeTo(diffPath);
![image](https://user-images.githubusercontent.com/32069580/74311031-89c35580-4d94-11ea-883b-0dceae7f74b8.png)

**Comment by apathan123** [comment]
Looks like it was still using old version... something to do with eclipse still lookign for old jar. sorted after claening .m2 repository. 
Thanks
