### ISSUE TITLE
Feature: output only pages with differences

### ISSUE THREAD

**Issue by pensionarchitects-ben** [red6/pdfcompare#68]
I have huge documents that needs to be compared (1000-2000 pages) most of them are completely the same but sometimes there are 1 or 2 pages that show a differences. To find these differences easier would it be possible to only output the pages with differences?

Greetings
Ben

**Comment by finsterwalder** [comment]
I added an environment setting "addEqualPagesToResult" that you can set to false.
Is that a good solution to your problem?
You'll find it in version 1.1.46, that I just release now, so it might take a few hours to show up in maven central.

**Comment by pensionarchitects-ben** [comment]
Thank you for your quick reaction and solution
