### ISSUE TITLE
Question about full pages exlusions

### ISSUE THREAD

**Issue by jradom** [red6/pdfcompare#72]
Hello

Let's say I have 2 files which can have from 2 to X number of pages.  I can 2 and 2 or 3 and 3 or 15 and 15, etc.  I always want to compare only the first 2 pages and exclude all others to the end.  I want to use only one conf file.  Please, suggest what is the best way will be to do that?  Also, can source and target files be in any separate directories?  What are the changes in the last version vs 2 versions back?

Thanks a lot in advance

Jeff

**Comment by finsterwalder** [comment]
It does not hurt to add pages in an exclude file, that don't exist. So you could write a file that excludes the maximum amount of pages that you expect like this:
exclusions: [
    { page: 3 },
    { page: 4 },
    ....
    { page: 15 }
]
There is no easier way currently.

Or you could do it programmatically:
pdfCompare = new PdfComparator("expected.pdf", "actual.pdf")
for( in i = 2; i++; i < 20) {
    pdfCompare.withIgnore(new PageArea(i));
}
or similar.

**Comment by jradom** [comment]
It'l be nice to have something like Pages: 2-6, 8-10, 12, 14

**Comment by finsterwalder** [comment]
With the current implementation and format, that is not so trivial to do.
And it's not high on my list of things to do...
Feel free to implement something and create a merge request. ;-)
