### ISSUE TITLE
Cannot use pixel tolerance margin

### ISSUE THREAD

**Issue by LeN1Sensibl** [red6/pdfcompare#73]
Hello
I'm using your library for almost two years and I'd like to thank for this. It is really helpful.
I'm facing now some difficulties with the tolerance percentage, that doesn't seem to work.

I've tried locally with this config 
```javascript
imageCacheSizeCount=30
maxImageSizeInCache=100000
mergeCacheSizeMB=100
swapCacheSizeMB=100
documentCacheSizeMB=200
parallelProcessing=true
overallTimeoutInMinutes=15
allowedDifferenceInPercentPerPage=90
```

This config on a local run is giving me an error as I have some noisy pixels failure, but definitely not 90% of the page.
I also noticed that a valid local run, is always failing for noisy pixel on a bamboo plan.
Here is this "noisy pixel" example
<img width="830" alt="Screenshot 2020-05-19 at 17 54 54" src="https://user-images.githubusercontent.com/32201769/82349983-0c465b80-99fb-11ea-90ee-2634ac343a1d.png">

Am I doing something wrong in the config?
Thank you in advance for your help

**Comment by finsterwalder** [comment]
Let me first ask a simple question: How did you apply the configuration? Did you put an application.conf file on the root of the classpath? Have you made sure, your changes to the config actually take effect?
Could you try to configure the setting via API? As in:
new PdfComparator("expected.pdf", "actual.pdf")
	.withEnvironment(new SimpleEnvironment().setAllowedDiffInPercent(90.0))
	.compare();
Just to see whether that works? Because when it does, it's probably a problem that your configuration is not done right and does not take any effect.
I did double check, that the feature works...

**Comment by finsterwalder** [comment]
Did you find a solution? Or does the problem persist?
If it's solved, please close this issue. Otherwise we can try to solve it together...

**Comment by LeN1Sensibl** [comment]
Sorry, was drowned by job...
So I could try it as you said via API settings. It works.
It solves my issue on not having the possibility to use tolerancy.
Still cannot understand why I have these noisy pixels on a bamboo server run that I don't have on a local run

**Comment by finsterwalder** [comment]
I noticed that I had small one pixel differences before, when using different JDKs (JDK8 vs. JDK11).
But I guess I can't really help you there. ;-) But I'm glad your PdfCompare issue could be solved. Then your application.conf file was most likely not reachable on the classpath.

**Comment by LeN1Sensibl** [comment]
Maybe to explain it for further users:
In my condition, the application.conf files is in fact not reachable because it is run on a server where I don't have the end and managed by others administrators (bamboo integration in a big company).
So what I did as @finsterwalder said, I put the config as an API settings, and defined this parameter as an environment variable.

`new PdfComparator(expected, actual).withEnvironment(getEnvironment());`

`private static SimpleEnvironment getEnvironment() {
        SimpleEnvironment simpleEnvironment = new SimpleEnvironment()
                .setNrOfImagesToCache(60)
                .setMaxImageSize(200000)
                .setMergeCacheSize(200)
                .setSwapCacheSize(200)
                .setDocumentCacheSize(400)
                .setParallelProcessing(true)
                .setOverallTimeout(15);
        String tolerance = System.getProperty("pdf.tolerance");
        if (tolerance != null && !tolerance.isEmpty()) {
            return simpleEnvironment.setAllowedDiffInPercent(Double.parseDouble(tolerance));
        }
        return simpleEnvironment;
    }`

So in thuis way I define a bamboo variable "pdf.tolearance" that is used on the server.
By default locally I don't have this issue so I don't need it. On the other way the same environment variable can be define locally to run the build with if you want it automated, or just adapting the code to force it locally works also
