### ISSUE TITLE
Comparison Result PDF showing a part of a file only in Green

### ISSUE THREAD

**Issue by AshokVijayk** [red6/pdfcompare#77]
A portion of a page is shown in green but there are no text differences .  I suspected that it could be pixel differences so I configured the pixel differences to be ignored as 1 but still that portion is showed in green.

**Comment by finsterwalder** [comment]
Setting the allowedDifferenceInPercentPerPage does not remove the marking of differences. It only influences, whether CompareResult.isEqual() evaluates to true or false. 
When you have areas of a page marked as different, then there are differences in rendered pixel color in that area. For whatever reason.

**Comment by AshokVijayk** [comment]
Thanks for the reply.  The portion i have mentioned above does not have differences does not have differences either in the text rendered or the color of the text except a slight alignment change.  Does the comparison marks the alignment differences too?

**Comment by finsterwalder** [comment]
PdfCompare does a pixel by pixel comparison only. It does not analyse the PDF or the text. So yes, changes in alignment are marked as difference.
