### ISSUE TITLE
Pdfcompare is not being highlighted.used version 1.1.50 dependency. Only 1 additional textpresent in destination file. In result file that extra text is not highlighted 

### ISSUE THREAD

**Issue by kavyass-code** [red6/pdfcompare#78]

**Comment by finsterwalder** [comment]
With this very general description, I can't really help.
Do I understand correctly:
Lets say you call PdfCompare like this:
`new PdfComparator("expected.pdf", "actual.pdf").compare().writeTo("diffOutput");`
You have two PDFs, I call them expected.pdf and actual.pdf here. The actual file has some extra text, that is not present in the expected file. But the result PDF called diffOutput.pdf here, does not show any markings for that? Where the actual.pdf has some extra text, the diffOutput.pdf file simply shows white?

The only situation, how I could see this happen is, when this extra text is encoded in a way that PdfBox, the underlying library I use to render PDFs to images, can't render it. Pdf is a very complex format and I noticed before, that sometimes graphics don't show up properly.
