### ISSUE TITLE
Best/Easiest way to exclude whole pages from the comparison?

### ISSUE THREAD

**Issue by PascalSchumacher** [red6/pdfcompare#8]
```
exclusions: [
    {
        page: 1
        x1: 0
        y1: 0
        x2: 9999
        y2: 9999
    }
]
```
works fine. I'm just wondering if there is a better/easier way?

**Comment by finsterwalder** [comment]
There is no other way so far, because I didn't think of this usecase. ;-)
Maybe it's a better idea to allow for an exclusion with only page and no coordinates.
I will look into it.

**Comment by finsterwalder** [comment]
I just release a new version 1.1.21, which allows to only specify a page and no coordinates, like:
exclusions: [
    { page: 1 }
]

Should be in maven central in a couple of hours.

**Comment by PascalSchumacher** [comment]
Thank you very much!
