### ISSUE TITLE
application.conf file location

### ISSUE THREAD

**Issue by steevi2307** [red6/pdfcompare#80]
Hi,

It's been a long time that i not use java but I succeeded to use the pdfcompare tool inside eclipse IDE an make a jar file that can be used from my .NET application.

But I don't understand how to use the application.conf file to allowed difference in percent ...
I tried to put this file in most of all directory but it doesn't seems to work.

Can you tell me what's wrong ? Pdfs are attached

![2020-08-18_084714](https://user-images.githubusercontent.com/69839035/90479938-c438f100-e12f-11ea-8782-edb2ed8a5bf4.png)

[New (P1).pdf](https://github.com/red6/pdfcompare/files/5088690/New.P1.pdf)
[Old (P1).pdf](https://github.com/red6/pdfcompare/files/5088691/Old.P1.pdf)

Thanks :)

**Comment by finsterwalder** [comment]
application.conf needs to be on the Java classpath.
Here this probably means, that it needs to be in src/main/resources.
When you create a jar, you can either include the application.conf file, which makes it easy to access, but hard to change. Or you need to make sure, when you start the jar, that your application.conf file is in a location, that is part of the classpath.

**Comment by finsterwalder** [comment]
Alternatively you could also set the config programmatically.
Have a look at IntegrationTest.whenMorePixelsAreDifferentThanAllowedDiffInPercentResultIsNotEqual() for an example.

**Comment by finsterwalder** [comment]
And another way: You can also use a system environment variable to do the configuration.

**Comment by steevi2307** [comment]
Ok, it seems to work with that code 

final CompareResult result = new PdfComparator(x, y).withEnvironment(new SimpleEnvironment().setAllowedDiffInPercent(5)).compare();
if (result.isNotEqual()) {
			System.out.println("Differences are found");
			result.writeTo(z);
			System.exit(1);
		}

But, if I take the entire document, it told me correctly that both documents are not equal but the resultfile show all differences ... is there a way to only show differences that are less than 5% of pixel difference ?

![image](https://user-images.githubusercontent.com/69839035/90502501-34ef0600-e14e-11ea-87cc-282ad73c2200.png)

Thanks

**Comment by finsterwalder** [comment]
Currently there is not. You always get all the differences.

**Comment by steevi2307** [comment]
Do you think it will be possible in a near future as an improvement ?

**Comment by finsterwalder** [comment]
There is a setting: addEqualPagesToResult
When you set that to false, pages that are equal (or where the difference is below the allowed percentage) are not added to the result. Is that what you want?

**Comment by steevi2307** [comment]
Actually, it's working very well but the best for me would be to have all pages with :
- initialpages if the % is not reached
- colored pages if the % is reached

Do you think it's possible ?

Thanks ;)

**Comment by finsterwalder** [comment]
Possible is everything. It's Software after all. ;-) But not everything makes sense...

Including the pages from the expected or actual PDF file unchanged, even though they have differences, does not make sense to me. That would be confusing and would go against the basic concept of PdfCompare, IMHO. The only thing that would make sense to me is: Mark those pages somehow differently. Similar to ignored areas, that get a yellow background. So you can still see that there are differences, but you also immediately see, that they have been ignored.

But doing that is not trivial. You only know at the end, whether the number of differing pixels is above or below the threshold of allowedDiffInPercent. But the margins are drawn during the rendering. :-/

**Comment by steevi2307** [comment]
OK, I will see what's the best later ;)
Thanks for your advices

**Comment by finsterwalder** [comment]
I updated the README to more clearly describe the possibilities to specify a config file
