### ISSUE TITLE
Configuration file persistence

### ISSUE THREAD

**Issue by gastendonk** [red6/pdfcompare#85]
A central persistence class is needed for loading and saving the configuration file. It is currently the case that any other configuration parameters would be lost if the exclusions were saved (see ExclusionsPanel.saveExclusionFile).

**Comment by finsterwalder** [comment]
Exclusion files don't contain configurations. They only contain exclusions. So saving an exclusion files does not change any configurations.
Configurations can't be saved at all at the moment. They are only read as described in the README.
