### ISSUE TITLE
how to get a jar CLI and run it from command line

### ISSUE THREAD

**Issue by jradom** [red6/pdfcompare#87]
Hi Malte,

I use your toll from Java code and like it a lot because it works.  Now I might need to call it as CLI from Typescript and saw in Readme  a possibility to use CLI with now details.  Please, let me know how if possible I can use it?

Thanks

Jeff

**Comment by finsterwalder** [comment]
You can download the jar file from maven central.
The easiest way to get there is to click on the "maven-central" tag on top of the README.
There you can download the full.jar variant.

**Comment by jradom** [comment]
great, let me try that.  Does it have the same capabilities which I have my
tests running using Java code?  That's great because your tool is really
great and I'll be able to reuse the flows I nave already and expand more
tests

Thanks a lot

Jeff

**Comment by jradom** [comment]
Malte,

I've just downloaded but do you by any chance have some samples how to
configure CLI with exclusion areas, threshold, etc?  Oh,  if it has UI then
is it a way to turn it off?  I plan to call it from Typescripts

Thanks a lot in advance

Jeff

**Comment by finsterwalder** [comment]
There is only one jar file. So yes, it's the same you use in your project.

**Comment by jradom** [comment]
I see, but about my other few short questions above?

**Comment by jradom** [comment]
Just ran it now and got this result
![image](https://user-images.githubusercontent.com/20550461/98650175-60b4fe80-22ed-11eb-96ef-022cf0bd8cb5.png)

**Comment by jradom** [comment]
I didn't see a diff file but kinda still not very clear how to set parameters.  tried help and didn't get much

**Comment by jradom** [comment]
I've got the file but is it a way to get a return status like true/false or pass/fail?

**Comment by finsterwalder** [comment]
I just released a new version: 1.1.55 that has a lot more options on the CLI. Incl. specifying an exclusion file.
Parameters can be set via environment variable or by passing -P. I added a description to the README.

**Comment by finsterwalder** [comment]
The CLI gives you return codes: 0 for equal docs, 1 for unequal docs and 2 for errors occurred.
I added this to the help output. Will show up in version 1.1.56

**Comment by finsterwalder** [comment]
BTW: The diff file can be written via the -o parameter, as described in the help.

**Comment by jradom** [comment]
Hi Malte,

I'm starting to implement Typescript/Cypress/Cucumber PDF file comparison.
Below is a sample code

Then(/^compare baseline (.*) and actual (.*) reports with diff report
(.*)$/, function (baseline: string, actual: string, diff: string) {
  const inputComparePdf = 'java -jar pdfcompare-1.1.60-full.jar + '
    + baseline + ' ' + actual + ' -o diff  > Downloads/final_report_bad_output';
  cy.exec(inputComparePdf, {failOnNonZeroExit:
false}).its('code').should('eq', 0);
});


I t was clear to me and worked great in java but how can I include
Excusions file into a Pdfcompare CLI?  Please, let me know


Thanks


Jeff

**Comment by finsterwalder** [comment]
If you call pdfcompare cli with -h, you will get a command line help.
usage: java -jar pdfcompare-x.x.x-full.jar [EXPECTED] [ACTUAL]
`
Return codes:
   0 for documents are equal
   1 for documents differ
   2 for errors occured

 -actpwd,--actual-password <actual-password>       Provide a password for the actual file
 -exppwd,--expected-password <expected-password>   Provide a password for the expected file
 -h,--help                                         Displays this text and exit
 -o,--output <output>                              Provide an optional output file for the result
 -x,--exclusions <exclusions>                      Provide an optional file with exclusions
`

**Comment by finsterwalder** [comment]
difference percentage can't be passed via command line currently. You would have to provide a config file for that. See the readme about how to do that.

**Comment by jradom** [comment]
I see, thanks. But what about setting percentage of comparison?

Thanks

Jeff

**Comment by jradom** [comment]
Sorry, I’ve missed your answer for percentage setting
