### ISSUE TITLE
Output PDF wtih data from 2nd pdf only mark in red color

### ISSUE THREAD

**Issue by geekyzan** [red6/pdfcompare#88]
Hey red6 :),
I want an output pdf that shows the difference from the 2nd file only i.e the different mark as red color(no data from 1st pdf).In which method I have to do those changes so that only the difference from 2nd pdf will be printed in the output pdf.
(Note: I have attached my output which shows overlapping text in the output, and I want only red highlighted text only)
![issue1](https://user-images.githubusercontent.com/72064428/101919837-0f9c7100-3bf1-11eb-96db-bef0fdf7d5fc.PNG)

**Comment by finsterwalder** [comment]
Did that solve your problem?
