### ISSUE TITLE
Is it possible not to show where actual pixels were?

### ISSUE THREAD

**Issue by YashUoM** [red6/pdfcompare#97]
Since it is little messy when both actual and expected pixels are marked in the output, is there a way to mark only one set of pixels either actual or expected in the output?

**Comment by finsterwalder** [comment]
You can configure the color of expected and actual pixels. When you set one to white or black, they do not distract.
See the readme how to configure this.

**Comment by YashUoM** [comment]
yes white will do the trick. thanks
