### ISSUE TITLE
Page exclusions

### ISSUE THREAD

**Issue by jayalakshmijayant** [red6/pdfcompare#98]
Hello,
First of all, thanks for this utility. I am slightly confused as to how to get the coordinates for the exclusions. I read the help comments in that class, looks like something is off.
     * @param page Page number starting with 1
     * @param x1   x-coordinate of the upper left corner of the rectangle
     * @param y1   y-coordinate of the upper left corner of the rectangle
     * @param x2   x-coordinate of the lower right corner of the rectangle
     * @param y2   y-coordinate of the lower right corner of the rectangle
Is this correct ?
This actually only takes into account the upper left and lower right of the rectangular block, but upper right and lower left are not considered. I tried with so many combination, and ran into issues. Could someone please help me out here. 
Thank you !

**Comment by finsterwalder** [comment]
Exclusions are always specified as rectangles. A rectangle is fully specified by providing two points in a coordinate systems. The upper left point of the rectangle and the lower right point of the rectangle. When you specify those two points, you can draw a rectangular shape with horizontal and vertical lines.
In the following picture the two stars are the points that are specified. The plus signs don't need to be specified.

*---------+
|            |
+---------*

Example:
x1 = 20
y1 = 30
x2 = 100
y2 = 150
draws four lines:
20, 30 => 100, 30
20, 30 => 20, 150
100, 30 => 100, 150
20, 150 => 100, 150

**Comment by jayalakshmijayant** [comment]
Thank you so much for explaining this !
I was using "pt" as unit of measurement in PDF and trying to use the API instead of .conf file. Once I corrected it, I got the correct results.
